# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r: bioc-devel
warnings_are_errors: false
cache: packages

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
    - covr

after_success:
    - travis_wait 40 Rscript -e 'library(covr); codecov()'
